// flow-typed signature: 4bd284a1d73633b84c5bc36a5033100d
// flow-typed version: <<STUB>>/react-apollo_v2.0.4/flow_v0.69.0
import type { DocumentNode, VariableDefinitionNode } from "graphql";

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-apollo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "react-apollo" {
  declare type NetworkStatus = 1 | 2 | 3 | 4 | 6 | 7 | 8;

  declare type MutationFunc<TResult, TVariables> = (
    opts: MutationOpts<TVariables>
  ) => Promise<ApolloQueryResult<TResult>>;

  declare type GraphqlData<TResult, TVariables> = GraphqlQueryControls &
    TResult & {
      variables: TVariables,
      refetch: (variables?: TVariables) => Promise<ApolloQueryResult<any>>
    };

  declare type ChildProps<TOwnProps, TResult, TVariables: Object = {}> = {
    data: GraphqlData<TResult, TVariables>,
    mutate: MutationFunc<TResult, TVariables>
  } & TOwnProps;

  // back compat
  declare type DefaultChildProps<P, R> = ChildProps<P, R, {}>;

  declare type ErrorPolicy = "none" | "ignore" | "all";

  declare type RefetchQueriesProviderFn = (
    ...args: any[]
  ) => string[] | PureQueryOptions[];

  declare type MutationOpts<TVariables> = {
    variables?: TVariables,
    optimisticResponse?: Object,
    refetchQueries?: string[] | PureQueryOptions[] | RefetchQueriesProviderFn,
    update?: MutationUpdaterFn<*>,
    errorPolicy?: ErrorPolicy,
    $call?: empty // Not function
  };

  declare type QueryOpts<TVariables> = {
    ssr?: boolean,
    variables?: TVariables,
    fetchPolicy?: FetchPolicy,
    pollInterval?: number,
    skip?: boolean,
    errorPolicy?: ErrorPolicy,
    $call?: empty // Not function
  };

  declare interface GraphqlQueryControls {
    error?: ApolloError;
    networkStatus: NetworkStatus;
    loading: boolean;
    variables: Object;
    fetchMore: (
      fetchMoreOptions: FetchMoreQueryOptions & FetchMoreOptions
    ) => Promise<ApolloQueryResult<any>>;
    refetch: (variables?: Object) => Promise<ApolloQueryResult<any>>;
    startPolling: (pollInterval: number) => void;
    stopPolling: () => void;
    subscribeToMore: (options: SubscribeToMoreOptions) => () => void;
    updateQuery: (
      mapFn: (previousQueryResult: any, options: UpdateQueryOptions) => any
    ) => void;
  }

  declare interface OptionProps<TProps, TResult, TVariables> {
    ownProps: TProps;
    data: GraphqlData<TResult, TVariables>;
    mutate: MutationFunc<TResult, TVariables>;
  }

  declare type OptionDescription<TProps, TVariables> =
    | QueryOpts<TVariables>
    | MutationOpts<TVariables>
    | ((props: TProps) => QueryOpts<TVariables> | MutationOpts<TVariables>);

  declare type NamedProps<P, R> = P & {
    ownProps: R
  };

  declare interface OperationOption<
    TResult: {},
    TProps: {},
    TChildProps: {},
    TVariables: {}
  > {
    +options?: OptionDescription<TProps, TVariables>;
    props?: (
      props: OptionProps<TProps, TResult, TVariables>
    ) => TChildProps | ChildProps<TProps, TResult, TVariables>;
    +skip?: boolean | ((props: any) => boolean);
    name?: string;
    withRef?: boolean;
    shouldResubscribe?: (props: TProps, nextProps: TProps) => boolean;
    alias?: string;
  }

  // Third argument of TMergedProps should be TVariables, but generics order
  // is preserved for backward compatibility.
  declare interface OperationComponent<
    TResult: Object = {},
    TOwnProps: Object = {},
    TVariables: Object = {},
    TMergedProps: Object = ChildProps<TOwnProps, TResult, TVariables>
  > {
    (
      component: React$ComponentType<TMergedProps>
    ): React$ComponentType<TOwnProps>;
  }

  declare function graphql<TResult, TProps, TChildProps, TVariables>(
    document: DocumentNode,
    operationOptions?: OperationOption<TResult, TProps, TVariables, TChildProps>
  ): OperationComponent<TResult, TProps, TVariables, TChildProps>;

  declare type WithApolloOptions = {
    withRef?: boolean
  };

  declare function withApollo<TProps>(
    component: React$ComponentType<{ client: ApolloClient } & TProps>,
    operationOptions?: WithApolloOptions
  ): React$ComponentType<TProps>;

  declare interface IDocumentDefinition {
    type: DocumentType;
    name: string;
    variables: VariableDefinitionNode[];
  }

  declare function parser(document: DocumentNode): IDocumentDefinition;

  declare interface Context {
    client?: ApolloClient;
    [key: string]: any;
  }

  declare interface QueryTreeArgument {
    rootElement: React$Element<*>;
    rootContext?: Context;
  }

  declare interface QueryResult {
    query: Promise<ApolloQueryResult<mixed>>;
    element: React$Element<*>;
    context: Context;
  }

  declare function walkTree(
    element: React$Element<*>,
    context: Context,
    visitor: (
      element: React$Element<*>,
      instance: any,
      context: Context
    ) => boolean | void
  ): void;

  declare function getDataFromTree(
    rootElement: React$Element<*>,
    rootContext?: any,
    fetchRoot?: boolean
  ): Promise<void>;

  declare function renderToStringWithData(
    component: React$Element<*>
  ): Promise<string>;

  declare function cleanupApolloState(apolloState: any): void;
}
